//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TruckersEntities : DbContext
    {
        public TruckersEntities()
            : base("name=TruckersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cash> Cash { get; set; }
        public virtual DbSet<Commission> Commission { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<LoadType> LoadType { get; set; }
        public virtual DbSet<Queue> Queue { get; set; }
        public virtual DbSet<SeriesPrice> SeriesPrice { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
